services:
  cv_ai:
    container_name: cv_ai
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000" 
    volumes:
      - ../:/app
    networks:
      - cv_network

    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  cv_network:
    external: true